#!/bin/bash
# Setup conda activation hooks for HEASoft environment
#
# Run this ONCE after creating the conda environment:
#   conda activate swift-photom
#   bash scripts/setup_conda_hooks.sh
#
# After setup, HEASoft and CALDB will be initialized automatically
# whenever you run: conda activate swift-photom

set -e

# Check we're in a conda environment
if [ -z "$CONDA_PREFIX" ]; then
    echo "ERROR: No conda environment active."
    echo "Run: conda activate swift-photom"
    exit 1
fi

ENV_NAME=$(basename "$CONDA_PREFIX")
echo "Setting up HEASoft activation hooks for environment: $ENV_NAME"
echo "CONDA_PREFIX: $CONDA_PREFIX"

# Create activation/deactivation directories
ACTIVATE_DIR="$CONDA_PREFIX/etc/conda/activate.d"
DEACTIVATE_DIR="$CONDA_PREFIX/etc/conda/deactivate.d"
mkdir -p "$ACTIVATE_DIR" "$DEACTIVATE_DIR"

# Determine HEASoft paths
# For conda-installed HEASoft, headas-init.sh may be in different locations
HEADAS_INIT=""
if [ -f "$CONDA_PREFIX/headas-init.sh" ]; then
    HEADAS_INIT="$CONDA_PREFIX/headas-init.sh"
elif [ -f "$CONDA_PREFIX/heasoft/headas-init.sh" ]; then
    HEADAS_INIT="$CONDA_PREFIX/heasoft/headas-init.sh"
elif [ -n "$HEADAS" ] && [ -f "$HEADAS/headas-init.sh" ]; then
    # Use existing HEADAS if set (manual install)
    HEADAS_INIT="$HEADAS/headas-init.sh"
fi

if [ -z "$HEADAS_INIT" ]; then
    echo "WARNING: Could not find headas-init.sh"
    echo "Looked in:"
    echo "  - $CONDA_PREFIX/headas-init.sh"
    echo "  - $CONDA_PREFIX/heasoft/headas-init.sh"
    echo "  - \$HEADAS/headas-init.sh"
    echo ""
    echo "If HEASoft is installed elsewhere, set HEADAS first:"
    echo "  export HEADAS=/path/to/heasoft/arch"
    echo "  bash scripts/setup_conda_hooks.sh"
    exit 1
fi

# Determine CALDB path
# Check conda env first, then fall back to existing CALDB
if [ -d "$CONDA_PREFIX/caldb" ]; then
    CALDB_BASE="$CONDA_PREFIX/caldb"
elif [ -n "$CALDB" ] && [ -d "$CALDB" ]; then
    CALDB_BASE="$CALDB"
else
    echo "WARNING: CALDB not found."
    echo "Please set CALDB environment variable:"
    echo "  export CALDB=/path/to/caldb"
    echo "  bash scripts/setup_conda_hooks.sh"
    exit 1
fi

echo "Found HEASoft init: $HEADAS_INIT"
echo "CALDB base: $CALDB_BASE"

# Create activation script
ACTIVATE_SCRIPT="$ACTIVATE_DIR/heasoft.sh"
cat > "$ACTIVATE_SCRIPT" << 'ACTIVATE_EOF'
#!/bin/bash
# HEASoft activation for swift-photom environment
# Auto-generated by setup_conda_hooks.sh

# Save pre-activation state for clean deactivation
export _SWIFT_PHOTOM_OLD_PATH="${PATH:-}"
export _SWIFT_PHOTOM_OLD_HEADAS="${HEADAS:-}"
export _SWIFT_PHOTOM_OLD_CALDB="${CALDB:-}"

ACTIVATE_EOF

# Add the actual initialization (with resolved paths)
cat >> "$ACTIVATE_SCRIPT" << ACTIVATE_EOF

# Initialize HEASoft
if [ -f "$HEADAS_INIT" ]; then
    source "$HEADAS_INIT"
fi

# Set up CALDB
export CALDB="$CALDB_BASE"
if [ -d "\$CALDB/software/tools" ]; then
    export CALDBCONFIG="\$CALDB/software/tools/caldb.config"
    export CALDBALIAS="\$CALDB/software/tools/alias_config.fits"
fi
ACTIVATE_EOF

chmod +x "$ACTIVATE_SCRIPT"
echo "Created: $ACTIVATE_SCRIPT"

# Create deactivation script
DEACTIVATE_SCRIPT="$DEACTIVATE_DIR/heasoft.sh"
cat > "$DEACTIVATE_SCRIPT" << 'DEACTIVATE_EOF'
#!/bin/bash
# HEASoft deactivation for swift-photom environment
# Auto-generated by setup_conda_hooks.sh

# Restore pre-activation state
if [ -n "$_SWIFT_PHOTOM_OLD_PATH" ]; then
    export PATH="$_SWIFT_PHOTOM_OLD_PATH"
fi

# Unset HEASoft variables
unset HEADAS CALDB CALDBCONFIG CALDBALIAS
unset _SWIFT_PHOTOM_OLD_PATH _SWIFT_PHOTOM_OLD_HEADAS _SWIFT_PHOTOM_OLD_CALDB

# Restore old values if they existed
if [ -n "$_SWIFT_PHOTOM_OLD_HEADAS" ]; then
    export HEADAS="$_SWIFT_PHOTOM_OLD_HEADAS"
fi
if [ -n "$_SWIFT_PHOTOM_OLD_CALDB" ]; then
    export CALDB="$_SWIFT_PHOTOM_OLD_CALDB"
fi
DEACTIVATE_EOF

chmod +x "$DEACTIVATE_SCRIPT"
echo "Created: $DEACTIVATE_SCRIPT"

echo ""
echo "Setup complete!"
echo ""
echo "To test, deactivate and reactivate the environment:"
echo "  conda deactivate"
echo "  conda activate swift-photom"
echo ""
echo "Then verify with:"
echo "  echo \$HEADAS"
echo "  echo \$CALDB"
echo "  which uvotmaghist"
